### ISSUE TITLE
Style not applied when a geoserver layer added to canvas or legend using drag&drop

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geoserver-plugin#10]
seems that, because the plugin can't understand when the layer has been added, can't apply the relative style and a predefined style is applied by qgis

**Comment by volaya** [comment]
fixed in https://github.com/boundlessgeo/qgis-geoserver-plugin/commit/a3d22d89ceac25a7306b1c7ef8b789c7f208e576

**Comment by luipir** [comment]
confirmed
