### ISSUE TITLE
Plugin listed as  Invalid in qgis 3.6 Noosa

### ISSUE THREAD

**Issue by yaras-phoenix** [boundlessgeo/qgis-geoserver-plugin#108]
Win10 x64, QGIS 3.6 Noosa

I couldn't find the plugin in the official repository so I've just put the plugin data to:
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis-geoserver-plugin-master

When I open plugin manager in QGIS I see this:
![image](https://user-images.githubusercontent.com/37367584/57216685-db160b80-6ff0-11e9-8426-8603e73835e0.png)

Has anyone encountered such an issue?

**Comment by dakcarto** [comment]
Hi @yaras-phoenix,

Please read the [README](https://github.com/boundlessgeo/qgis-geoserver-plugin/blob/master/README.rst) on how to deploy or package the plugin using `paver`, i.e. you can not download an archive of this repository and use it directly.

**Comment by dakcarto** [comment]
Also, you will need to checkout the `qgis3` branch for compatibility with latest QGIS 3.

**Comment by yaras-phoenix** [comment]
I'm new to command line but I think I have installed paver: 

Requirement already up-to-date: Paver in e:\qgis_3_6\apps\python27\lib\site-packages (1.3.4)
Requirement already satisfied, skipping upgrade: six in e:\qgis_3_6\apps\python27\lib\site-packages (from Paver) (1.12.0)

But when I try to execute 'paver setup' or 'paver install', I get 'Build failed: Unknown task: setup'

P.S. I'm using OSGeo4w shell that comes with qgis.

P.P.S. If I get it right, qgis3 branch is now called 'master'.

**Comment by dakcarto** [comment]
@yaras-phoenix wrote:
> But when I try to execute 'paver setup' or 'paver install', I get 'Build failed: Unknown task: setup'

Ensure your current working directory is the root of the plugin's code checkout.

> P.P.S. If I get it right, qgis3 branch is now called 'master'.

Indeed. Sorry for the confusion there.

**Comment by yaras-phoenix** [comment]
Thanks for the hint. Changed directory to the proper one but now I get another issue. 'Paver setup' seems to work just fine but then:

- paver install

---> pavement.install
---> pavement.builddocs
git submodule init
fatal: not a git repository (or any of the parent directories): .git
sphinx-build -a  docs/source docs/build/html
Running Sphinx v2.0.1

Theme error:
no theme named 'boundless_doc' found (missing theme.conf?)


Captured Task Output:
---------------------

---> pavement.install
---> pavement.builddocs
git submodule init
sphinx-build -a  docs/source docs/build/html

Build failed running pavement.install: Subprocess return code: 2

P.S. I use OSGeo4W shell with git\cmd and git\bin added to its path variable.

I would prefer to post this to the mailing list but it's not working for some reason.
