### ISSUE TITLE
Drag&Drop from Browser to a workspace generate silent error

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geoserver-plugin#16]
the log says:

src/core/qgsmimedatautils.cpp: 111: (decodeUriList) [23224ms] raster:gdal:landcover:/home/ginetto/PROGRAMMING/GIS/GISDATA/qgis_sample_data/raster/landcover.img::
src/core/qgsmimedatautils.cpp: 47: (Uri) [0ms] encData: raster:gdal:landcover:/home/ginetto/PROGRAMMING/GIS/GISDATA/qgis_sample_data/raster/landcover.img::
src/core/qgsmimedatautils.cpp: 71: (Uri) [0ms] type:raster key:gdal name:landcover uri:/home/ginetto/PROGRAMMING/GIS/GISDATA/qgis_sample_data/raster/landcover.img supportedCRS: supportedFormats:
Traceback (most recent call last):
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/gui/explorertree.py", line 214, in dropEvent
    toUpdate = destinationItem.acceptDroppedUris(self, self.explorer, elements)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1237, in acceptDroppedUris
    return addDraggedUrisToWorkspace(uris, self.parentCatalog(), self.element, explorer, tree)
TypeError: addDraggedUrisToWorkspace() takes exactly 4 arguments (5 given)

probably an API disalignment

**Comment by volaya** [comment]
This seems to be fixed already. Draggin to wrokspace correctly publishes the layer. Please, reopen if needed
