### ISSUE TITLE
egg loading error on Ubuntu 15.10 - error during qgis startup

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geoserver-plugin#18]
Couldn't load plugin 'geoserverexplorer' from ['/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/python_dateutil-2.2-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/six-1.7.3-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/requests-2.0.1-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/gisdata-0.5.4-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/httplib2-0.9-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/nose_html-1.1-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/nose-1.3.4-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/coverage-3.7-py2.7-linux-x86_64.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/nose_html-1.1-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/processing', '/home/ginetto/.qgis2/python/plugins/ntv2_transformations', '/home/ginetto/PROGRAMMING/QGIS/QGIS-2.8/build/output/python', '/home/ginetto/.qgis2/python', '/home/ginetto/.qgis2/python/plugins', '/home/ginetto/PROGRAMMING/QGIS/QGIS-2.8/build/output/python/plugins', '/mnt/data/PROGRAMMING/QGIS/QGIS-2.8/build/output/python', '/home/ginetto/.qgis2/python/plugins', '/mnt/data/PROGRAMMING/IDE/Aptana_Studio_3/plugins/org.python.pydev_2.7.0.2013032300/pysrc/mnt/data/PROGRAMMING/IDE/Aptana_Studio_3/plugins/org.python.pydev_3.9.2.201502050007/pysrc', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2', '/home/ginetto/.qgis2//python', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs']

Traceback (most recent call last):
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-2.8/build/output/python/qgis/utils.py", line 196, in loadPlugin
    __import__(packageName)
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-2.8/build/output/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/__init__.py", line 9, in 
    from geoserverexplorer.qgis.catalog import *
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-2.8/build/output/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 17, in 
    import requests
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-2.8/build/output/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/requests-2.0.1-py2.7.egg/requests/__init__.py", line 53, in 
    from .packages.urllib3.contrib import pyopenssl
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-2.8/build/output/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/requests-2.0.1-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 43, in 
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

Python version:
2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010]

QGIS version:
2.8.3-Wien Wien, b0f6e30

Python path: ['/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/python_dateutil-2.2-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/six-1.7.3-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/requests-2.0.1-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/gisdata-0.5.4-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/httplib2-0.9-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/nose_html-1.1-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/nose-1.3.4-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/coverage-3.7-py2.7-linux-x86_64.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/nose_html-1.1-py2.7.egg', '/home/ginetto/.qgis2/python/plugins/processing', '/home/ginetto/.qgis2/python/plugins/ntv2_transformations', '/home/ginetto/PROGRAMMING/QGIS/QGIS-2.8/build/output/python', u'/home/ginetto/.qgis2/python', u'/home/ginetto/.qgis2/python/plugins', '/home/ginetto/PROGRAMMING/QGIS/QGIS-2.8/build/output/python/plugins', '/mnt/data/PROGRAMMING/QGIS/QGIS-2.8/build/output/python', '/home/ginetto/.qgis2/python/plugins', '/mnt/data/PROGRAMMING/IDE/Aptana_Studio_3/plugins/org.python.pydev_2.7.0.2013032300/pysrc/mnt/data/PROGRAMMING/IDE/Aptana_Studio_3/plugins/org.python.pydev_3.9.2.201502050007/pysrc', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2', u'/home/ginetto/.qgis2//python', '/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs']

**Comment by luipir** [comment]
is an urllib3 bug

http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

this affect all plugins using urllib3 :( and seems ubuntu doe not package an upgradet version!

**Comment by luipir** [comment]
can be solved using a higher version of requests in requirements.txt

why requirements is set to 2.0.1? ther is a minimal installation requirement depending on a specific platform?

**Comment by luipir** [comment]
2.5.0 is the minimal version that allow compilation in Ubuntu 15.10

**Comment by volaya** [comment]
I guess that was the version that was the latest at the time of writing
that requirements file. Can you change it to the version that works fine in
your system (or higher)?

On Tue, Nov 3, 2015 at 1:30 PM, Luigi Pirelli <notifications@github.com>
wrote:

> 2.5.0 is the minimal version that allow compilation in Ubuntu 15.10
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boundlessgeo/qgis-geoserver-plugin/issues/18#issuecomment-153337948>
> .
>



-- 
Victor Olaya
Software Engineer | Boundless <http://boundlessgeo.com/>
volaya@boundlessgeo.com
@boundlessgeo <http://twitter.com/boundlessgeo/>

**Comment by luipir** [comment]
ok, I'll set the minimal version that works in my 15.10 (that is latest ubuntu)

requests 2.5 was release 2014-12-01
