### ISSUE TITLE
Categorised qgis layer imported as geoserver rule based layer

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geoserver-plugin#19]
a vector layer that is styled categorised is imported in geoserver correctly, but the style is set as rule based. Thi create some side effects in case a category is NULL => rulemased is empty and overpass all category

you can test is qith quickstart.qgs project as usual

![screenshot from 2015-11-06 15-56-21](https://cloud.githubusercontent.com/assets/3344634/11001414/01fe403c-849f-11e5-90c1-813f645274ba.png)

**Comment by volaya** [comment]
This is a consequence of using the QGIS SLD export. QGIS exports always as
a rule based. This might be another reason to move away from it and create
our own exporter...

On Fri, Nov 6, 2015 at 4:57 PM, Luigi Pirelli <notifications@github.com>
wrote:

> Assigned #19
> <https://github.com/boundlessgeo/qgis-geoserver-plugin/issues/19> to
> @volaya <https://github.com/volaya>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boundlessgeo/qgis-geoserver-plugin/issues/19#event-457060279>
> .
>



-- 
Victor Olaya
Software Engineer | Boundless <http://boundlessgeo.com/>
volaya@boundlessgeo.com
@boundlessgeo <http://twitter.com/boundlessgeo/>

**Comment by gioman** [comment]
@volaya @luipir should we assume that for now we stick with the qgis sld exporter?

**Comment by luipir** [comment]
yes, I think so

**Comment by gioman** [comment]
Ok closing then.
