### ISSUE TITLE
Removing a "layer" from workspace does not remove it's style

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geoserver-plugin#22]
to replicate:

1) upload a layer
2) verify a correspondent style has been created (with Gwc layer, ando so on)
3) remove layer from workgroup
4) verify that the style has not been removed

**Comment by volaya** [comment]
There is an option for that ("Delete style when deleting layer"). Do you have it enabled?

**Comment by luipir** [comment]
Probabily not
