### ISSUE TITLE
Saving SLD from QGIS error 

### ISSUE THREAD

**Issue by Geoneer** [boundlessgeo/qgis-geoserver-plugin#28]
On Windows 7 64bits Enterprise:

What did I do:
- Added default Geoserver localhost installation
- port 8080
- default layers / styles
- add localhost geoserver to QGIS 2.12.2 Lyon with plugin
- edit style [giant polygon] in QGIS
- save the style in QGIS

next error occurred:

must be string or buffer, not tuple 
Traceback (most recent call last):
  File "C:/Users/A613256/.qgis2/python/plugins\geoserverexplorer\gui\explorer.py", line 98, in run
    command(*params)
  File "build\bdist.win32\egg\geoserver\style.py", line 108, in update_body
    self.body_href, "PUT", body, headers)
  File "C:/Users/A613256/.qgis2/python/plugins\geoserverexplorer\geoserver\retry.py", line 14, in decorator
    raise e
TypeError: must be string or buffer, not tuple

Q: Did you see this bug also?

What to do:
1. workaround export SLD and put in the SLD editor?
2. fix this bug in .py files?

I did fork the source also. I'm thinking about to try to solve this bug so the SLD is put to Geoserver through REST.

**Comment by luipir** [comment]
are you saying you are using plugin source code (then paver packaging) or the version installed from qgis plugin repo?

**Comment by Geoneer** [comment]
I did install the plugin throught the default QGIS repository:

http://plugins.qgis.org/plugins/plugins.xml

**Comment by Geoneer** [comment]
![image](https://cloud.githubusercontent.com/assets/218929/11957533/9e8923e4-a8c2-11e5-8130-9bdb236fc953.png)

**Comment by Geoneer** [comment]
![image](https://cloud.githubusercontent.com/assets/218929/11957583/e0a38e4a-a8c2-11e5-9a91-d466a302766e.png)

**Comment by Geoneer** [comment]
![image](https://cloud.githubusercontent.com/assets/218929/11957599/f5787e48-a8c2-11e5-80c9-170582c191c1.png)

**Comment by Geoneer** [comment]
Geoserver:
![image](https://cloud.githubusercontent.com/assets/218929/11957632/221da8ce-a8c3-11e5-8d7e-37bb9bc296ef.png)

**Comment by Geoneer** [comment]
So I installed it from the default repos of the QGIS plugins.

**Comment by luipir** [comment]
ok...you installed from repo... but I can't reporduce your problem. You wrote:

- Added default Geoserver localhost installation
- port 8080
- default layers / styles
- add localhost geoserver to QGIS 2.12.2 Lyon with plugin
- edit style [giant polygon] in QGIS
- save the style in QGIS

in these steps there is no interaction with geoserver, but only saving polygon style in the qgis project. I suppose you applied a style to a polygon layer and imported the layer in the default geoserver worspace. Is it correct?
The error is during import? is during loading the layer from geoserver? when?

**Comment by Geoneer** [comment]
let's see:

#1 
![image](https://cloud.githubusercontent.com/assets/218929/11959693/f2146bf2-a8ce-11e5-97da-addd5ac58e46.png)

#2 
![image](https://cloud.githubusercontent.com/assets/218929/11959708/07b07028-a8cf-11e5-9ad7-fb42980d0596.png)

#3 
![image](https://cloud.githubusercontent.com/assets/218929/11959714/117691aa-a8cf-11e5-8805-cf874f25bfef.png)

#4 edit the style from the SLD
![image](https://cloud.githubusercontent.com/assets/218929/11959753/535ff9e4-a8cf-11e5-9290-cef8853b2efb.png)

#5 apply / save / close
![image](https://cloud.githubusercontent.com/assets/218929/11959760/658cf57c-a8cf-11e5-8c02-a0df8babcb3e.png)

**Comment by Geoneer** [comment]
So it happens when I want to edit the SLD file when double click on the Styles tree in the Geoserver explorer. In my case the style 'giant polygon'. 

If you've not got this error and you could save the QGIS style SLD to the Geoserver, how did you do this? Did you first add the layer to QGIS and edit the styling there?

**Comment by Geoneer** [comment]
A few things I have to make clear:
1. I'm using Geoserver for my internet data handling in WMS / CesiumJS
2. I'm using QGIS to edit the styling of the layers which are stored in Geoserver
3. My spatial data is in PostGIS 9.4 database, but at the moment I'm just testing with the Tasmania polygon in the default Geoserver Installtion
4. I run Geoserver manualy in Jetty 6.1.8
