### ISSUE TITLE
QGIS proxy settings not used?

### ISSUE THREAD

**Issue by rduivenvoorde** [boundlessgeo/qgis-geoserver-plugin#29]
Thanks for the work put into this plugin!

I'm testing this here on a windows environment behind a corporate proxy, and fail to get a connection with a catalog, actually not even a localhost:8080 one...

For QGIS to work with this proxy (eg get plugins etc) I use the QGIS Settings/ Network/Use proxy for web access. There I use 'HttpProxy' and fill in a Host and Port (no User/Password needed).

A quick look into the code, I'm not sure if the QGIS-network settings are taken into account...

Can somebody confirm that the plugins is working in a proxied environment.
OR confirm that the plugin is not working with a proxy (yet). In this case this can be seen as a feature request :-)

**Comment by luipir** [comment]
as far as I remember, actually the master version uses the QgsNetworkAccessManager through a workaroud by @elpaso. This issue shoudl be closed!

**Comment by gioman** [comment]
> This issue shoudl be closed!

then reopen if necessary.

**Comment by luipir** [comment]
should be managed thanks the introduction of the NetworkAccessManager class wrapper introduced by @elpaso

**Comment by rduivenvoorde** [comment]
Ok, thanks!

Will test next thursday when I'm behind that proxy again :-)

**Comment by luipir** [comment]
@rduivenvoorde I don't know exactly in what release version has been introduced the wrapper, it will subject of the contribution of the PyQGIS Cookbook. here the draft under revision: https://github.com/boundlessgeo/QGIS-Documentation/blob/auth_pyqgis_cookbook/source/docs/pyqgis_developer_cookbook/authentication.rst

btw, if not available, please test master
