### ISSUE TITLE
New style from QGIS layer... (Marker placement; Offset along line) are not saved in SLD.

### ISSUE THREAD

**Issue by laingit** [boundlessgeo/qgis-geoserver-plugin#37]
![image](https://cloud.githubusercontent.com/assets/1755240/14174391/4bbf5e96-f744-11e5-83b9-2ad8d9acb627.png)

**Comment by gioman** [comment]
@volaya should we assume that this is because of the actual limitations when exporting qgis styles to sld? https://github.com/boundlessgeo/qgis-geoserver-plugin/blob/master/docs/source/intro.rst#styling-limitations

**Comment by volaya** [comment]
@gioman Yes, those parameters are not used when creating the SLD style

**Comment by gioman** [comment]
So I'm closing this.

**Comment by laingit** [comment]
Geoserver gets the same result with a  different combination of stroke-dasharray and GraphicStroke (**It is odd, and very confusing**) http://docs.geoserver.org/stable/en/user/styling/sld/cookbook/lines.html#alternating-symbols-with-dash-offsets
