### ISSUE TITLE
Handling ogc:Literal tag

### ISSUE THREAD

**Issue by jgrocha** [boundlessgeo/qgis-geoserver-plugin#58]
Hi,

Some SLD styles are not properly converted to QGIS, because they use the `<ogc:Literal>` tag around the values.

For example, the default `simple_streams` Geoserver style is written as:

```
<Stroke>
	<CssParameter name="stroke">
		<ogc:Literal>#003EBA</ogc:Literal>
	</CssParameter>
	<CssParameter name="stroke-width">
		<ogc:Literal>2</ogc:Literal>
	</CssParameter>
</Stroke>
```

If the same style is written simple as:

```
<Stroke>
	<CssParameter name="stroke">#003EBA</CssParameter>
	<CssParameter name="stroke-width">2</CssParameter>
</Stroke>
```

it would be properly converted to QGIS.

Which would be the best way to handle this `<ogc:Literal>` tag within the plugin? Should we delete all  `<ogc:Literal>` and surrounding white spaces prior to any processing or should we change some regular expressions that handle this?

Regards!

**Comment by luipir** [comment]
good catch, 

may you prepare a really simple data set just a line o point with a use of ogc:literal?

ogc:Literal is introduced in http://www.opengeospatial.org/standards/se => SLD1.1, btw seems used more for ogc operators than to pass parameters.

I suggest to have a schema check to verify if the SLD is formally correct (I suppose yes, but better to check because I can't find other use of ogc:Literal)

ogc:Literal is used in Geoserver SLD as extension because this extension try to expand support from SLD1.0 to SLD1.1. Btw in SLD documentation literals are used for ogc function too.

waiting for a data set (simple geom + start SLD style + qgsi accepted sld) that can be used to create a convertor if this use of ogc:Literal is formally correct

**Comment by jgrocha** [comment]
Thanks @luipir for the feedback.

A useful dataset for testing styles with this tag `ogc:Literal` are some of the default Geoserver styles (styles that comes with the default Geoserver installation). For example, the default style `cite_lakes` is used to style the default layer `tasmania_water_bodies` from the default store `taz_shapes`.

I've attached the `tasmania_water_bodies` shapefile and the default `Lakes.sld` style.

[tasmania_water_bodies.zip](https://github.com/boundlessgeo/qgis-geoserver-plugin/files/700417/tasmania_water_bodies.zip)
[Lakes.sld.zip](https://github.com/boundlessgeo/qgis-geoserver-plugin/files/700419/Lakes.sld.zip)

If we use the qgis-geoserver-plugin to add this layer to QGIS, the style is not parsed correctly.

If we edit the style and remove all `ogc:Literal` tags, the style is properly interpreted and the render in QGIS is ok. The qgis accepted style `Lake-for-qgis-geoserver-plugin.sld` is also attached.

[Lake-for-qgis-geoserver-plugin.sld.zip](https://github.com/boundlessgeo/qgis-geoserver-plugin/files/700444/Lake-for-qgis-geoserver-plugin.sld.zip)

**Comment by luipir** [comment]
perfect, tnx

**Comment by luipir** [comment]
probably related:
https://hub.qgis.org/issues/15422

**Comment by jgrocha** [comment]
Hi @luipir,

It seems to me that the qgis-geoserver-plugin just do some conversions between QGIS and Geoserver SLD, on `qgis/sldadapter.py`, right?

Some `<ogc:Literal>` tags are already properly handled by QGIS. The SLD 1.0 schema already uses `<ogc:Literal>` tags. For example, the `<ogc:Literal>` is required in [Filter Encoding](http://docs.geoserver.org/latest/en/user/filter/filter_reference.html). For example, qgis-geoserver-plugin handles pretty well the default Geoserver style `popshade.sld`, which has `<ogc:Literal>` tags on filters.
```
          <ogc:Filter>
            <ogc:PropertyIsBetween>
              <ogc:PropertyName>PERSONS</ogc:PropertyName>
              <ogc:LowerBoundary>
                <ogc:Literal>2000000</ogc:Literal>
              </ogc:LowerBoundary>
              <ogc:UpperBoundary>
                <ogc:Literal>4000000</ogc:Literal>
              </ogc:UpperBoundary>
            </ogc:PropertyIsBetween>
          </ogc:Filter>
``` 
We might be able to solve this interoperability problem, just by hacking the regular expressions on `qgis/sldadapter.py`. Am I missing something else we need to change?
I'll try to hack `qgis/sldadapter.py` and make a PR, if it does makes sense to you.

**Comment by luipir** [comment]
for me it's ok, btw would be better to have a general solution, in the sense that would be better to solve the problem from the QGIS side, without adding patches to sldadapter.

I suppose (I didn't check) that ogc:Literal is correctly manage if it is associated to the a ogc operator (as in Filter, env, if etc etc) and not correctly managed if used outside this context.

btw, a temprorary patch usign sldadapter is really welcome :) and also a related test with source sld and expected one after conversion. Please give a look to the tests already available. That related with SLD are not concentrated in a unique file (My intention is to move them in a unique test suite). If it is possibile you can add here:
https://github.com/boundlessgeo/qgis-geoserver-plugin/blob/master/geoserverexplorer/test/symbologytests.py

thank you to contribute to the plugin dev

**Comment by jgrocha** [comment]
I've just made a [PR to QGIS](https://github.com/qgis/QGIS/pull/3996) to fixed it on the QGIS side, as @luipir suggested.

**Comment by gioman** [comment]
@jgrocha @luipir PR merged, can we close this?

**Comment by jgrocha** [comment]
@gioman Thanks for the reminder! I can check this Saturday. Reminder added to calendar.
