### ISSUE TITLE
MemoryError during layer upload

### ISSUE THREAD

**Issue by Toshakins** [boundlessgeo/qgis-geoserver-plugin#65]
Good day

I am trying to upload a 500Mb layer through the plugin. During upload I receive this error:
![capture5 png](https://cloud.githubusercontent.com/assets/413353/24260147/b1806f7e-0ffb-11e7-8011-680aa36a2652.png)

I have 32Gb of RAM and it's mostly free. My setup: qGIS 2.14 and Geoserver plugin is 0.5. OS is Windows 10.

What could possibly trigger such an error? Is it a known issue? Any ideas how to resolve that?

I am ready to give any additional information if needed.

**Comment by gioman** [comment]
@Toshakins raster? vector? shareable dataset? Version of Geoserver? running Geoserver on the same machine as QGIS?

**Comment by Toshakins** [comment]
@gioman 
Vector layer, shareable dataset, Geoserver 2.7.4 which runs remotely.

**Comment by gioman** [comment]
@Toshakins you send me it to giovanni.manghi@gmail.com I will give it a spin against a more recent version of the plugin and of Geoserver.

**Comment by luipir** [comment]
probably the solution is to stream the post content
http://stackoverflow.com/questions/2502596/python-http-post-a-large-file-with-streaming
or
http://stackoverflow.com/questions/35779879/python-requests-upload-large-file-with-additional-data

**Comment by luipir** [comment]
ho no sorry... in this case NetworkAccessmanager is proxing QgsNetowrkAccessmanager

**Comment by luipir** [comment]
@elpaso may upgrade NetworkAccessManager to use put(const QNetworkRequest&, QIODevice *) ?

**Comment by gioman** [comment]
Note for the issuer and developers: I was able to import the provided dataset using the master version of the plugin installed from git, and Boundless Suite 4.9. QGIS (2.18.4) and Suite running on the same machine (a Ubuntu 16.04 one).

**Comment by Toshakins** [comment]
@gioman @luipir Will upgrade and double check, let's close for now.

Sorry for disturbance and many thanks for helping investigate.

I will reopen if more evidence will be found.
