### ISSUE TITLE
python error when adding an endpoint with basic authentication

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geoserver-plugin#66]
`Could not connect to catalog: Traceback (most recent call last): File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 293, in addGeoServerCatalog cat = RetryCatalog(dlg.url, dlg.username, dlg.password) File "build/bdist.linux-x86_64/egg/geoserver/catalog.py", line 82, in __init__ self.setup_connection() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/geoserver/retry.py", line 26, in setup_connection disable_ssl_certificate_validation=self.disable_ssl_cert_validation) AttributeError: 'RetryCatalog' object has no attribute 'disable_ssl_cert_validation' `

but if the authentication credentials are added using the "configurations" panel it works as expected.

Testing using the Suite testing container.

**Comment by volaya** [comment]
looks like the version of gsconfig that is being used is an older one, particularly one before this fix made by @elpaso 

https://github.com/boundlessgeo/gsconfig/commit/db699376713d725905cf3a34caef35479947347a

Did you run paver setup recently?

**Comment by gioman** [comment]
@volaya 

installing master from dev repo I do not see the issue.

If I try against geoserver 2.11 I get

```
The specified catalog seems to be running an older
or unidentified version of GeoServer.
That might cause unexpected behaviour.
Do you want to add the catalog anyway?
```

but seems (not tested completely) to work.


```
Paver setup on master code revision gives:

---> pavement.setup
makedirs geoserverexplorer/ext-libs
easy_install -a -d /home/giovanni/Desktop/qgis-geoserver-plugin-master/geoserverexplorer/ext-libs httplib2==0.8
Searching for httplib2==0.8
Skipping development or system egg: httplib2 0.9.1
Reading https://pypi.python.org/simple/httplib2/
Download error on https://pypi.python.org/simple/httplib2/: [Errno 104] Connection reset by peer -- Some packages may not be found!
Couldn't find index page for 'httplib2' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 104] Connection reset by peer -- Some packages may not be found!
No local packages or download links found for httplib2==0.8
error: Could not find suitable distribution for Requirement.parse('httplib2==0.8') (--always-copy skips system and development eggs)


Captured Task Output:
---------------------

---> pavement.setup
makedirs geoserverexplorer/ext-libs
easy_install -a -d /home/giovanni/Desktop/qgis-geoserver-plugin-master/geoserverexplorer/ext-libs httplib2==0.8

Build failed running pavement.setup: Subprocess return code: 1
```

**Comment by volaya** [comment]
There was a problem with the version check, which was considering that 2.11 was less than the required 2.2 or higher. I fixed it, and i guess this issue can now be closed

**Comment by gioman** [comment]
@volaya Suite shipping Geoserver 2.11 is due soon, so I think it can be closed. A new version of the plugin should be made available at the same time or shortly after.
