### ISSUE TITLE
importing point layer with svg style stopped to work

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geoserver-plugin#68]
or maybe we just missing something in the testing endpoint?

```
Error uploading SVG icon to GeoServer: 401 Client Error: Unauthorized for url: http://suite.boundless.test:8080/geoserver/rest/resource/styles/camera_-394321632825054421.svg 
Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 101, in run
    command(*params)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/confirm.py", line 20, in publishLayer
    catalog.publishLayer(layer, workspace, True, name)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 503, in publishLayer
    sld = self.publishStyle(layer, overwrite, name) if style is None else None
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 171, in publishStyle
    self.uploadIcons(icons)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 187, in uploadIcons
    raise Exception ("Error uploading SVG icon to GeoServer:\n" + str(e))
Exception: Error uploading SVG icon to GeoServer:
401 Client Error: Unauthorized for url: http://suite.boundless.test:8080/geoserver/rest/resource/styles/camera_-394321632825054421.svg
```

**Comment by volaya** [comment]
Does the endopoint support SVG upload? 

Maybe the error is related to this? https://github.com/boundlessgeo/qgis-geoserver-plugin/pull/51/commits/f4ea569a004abdcc7745a4171106bd5f2e2dce89

We were using a suite-only method for uploading svgs, but now we use standard geoserver endpoints. @gioman Can you confirm it also fails on a local standard instllation of a recent geoserver?

**Comment by gioman** [comment]
@volaya it works ok with plugin installed from dev repo and a stock geoserver 2.11 instance. Other than that such layers are always loaded as wfs from the geoserver explorer, so this > https://github.com/boundlessgeo/qgis-geoserver-plugin/issues/55 still true.

**Comment by volaya** [comment]
mm, then i guess this issue can be closed?

**Comment by gioman** [comment]
@volaya Suite shipping Geoserver 2.11 is due soon, so I think it can be closed. A new version of the plugin should be made available at the same time or shortly after.
