### ISSUE TITLE
python error (and crash) when missing or mismatching certificte (when using PKI auth)

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geoserver-plugin#79]
```
"An error has occurred while executing Python code: 
TypeError: sslErrors() takes exactly 3 arguments (2 given) "
```

How to get that:

Assume a user wants to login in Geoserver with Geoserver Explorer and wants to use PKI

It enters QGIS authentication options and adds its own authentication profile certificate

then assume that he/she forgets to import the "authority" certificates (using the "manage certificates" button) or he/she imports old ones, no more valid for the endpoint that is needed ti use

when connecting with Geoserver Explorer the user is greeted with

![screenshot_20170609_114635](https://user-images.githubusercontent.com/1951107/26972765-069495a2-4d0b-11e7-86f3-3478c6c2c99e.png)

that i guess is expected, but when clicking on "ignore" this shows

![screenshot_20170608_185008](https://user-images.githubusercontent.com/1951107/26972780-16b215a4-4d0b-11e7-8387-e9edea64382d.png)

closing this error can sometimes lead to QGIS crash.

plugin: master
qgis: 2.18.9
gs: suite 4.9 (docker-compose > suite.boundless.test)

**Comment by luipir** [comment]
@gioman windows?

**Comment by gioman** [comment]
@luipir seen on windows and Linux

**Comment by luipir** [comment]
ha no... kde, sorry

**Comment by gioman** [comment]
@luipir I tested also on win

**Comment by luipir** [comment]
@gioman did you have added also CAs (Cert authorities?)

**Comment by gioman** [comment]
@luipir no that's the point. If I do of course works. This is about when missing to add all them, part of them or installing no more valid ones (for example the test ones we had for "boundless-test" do not work anymore for the containers/endopoints in compose (ex: suite.boundless.test).

**Comment by luipir** [comment]
@gioman I agree that crash or python is not expected, my question was to narrow the way to regenerate the error

**Comment by luipir** [comment]
the error is generated inside geoserver plugin NetworkAccessManager method

**Comment by luipir** [comment]
fixed with https://github.com/boundlessgeo/qgis-geoserver-plugin/commit/b997864d29ecd492905e838e32c8026b368877f9 but travis is having problems settinup test env
