### ISSUE TITLE
failing automated tests (tester plugin) for PKI connection against both suite 4.9 and 4.10

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geoserver-plugin#85]
Logs attached. This has been seen on Windows 10 but I think is the same also on Windows 7. BD 1.1 b6 and Geoserver explorer master.

[logs_pki.zip](https://github.com/boundlessgeo/qgis-geoserver-plugin/files/1106748/logs_pki.zip)

**Comment by luipir** [comment]
found the problem in the esoteric behavior of module load that are lost!

**Comment by luipir** [comment]
@elpaso travis goes well, but there is an anomaly doing rundockertest.sh locally where the PKI stuck because qgis gui does not start. I can't find why no PKI unit tests works correctly.

**Comment by luipir** [comment]
other errors found as attached log

**Comment by gioman** [comment]
new logs for win7/win10 runs against suite49 endpoint (all green in Linux running qgis on the host against both suite 49 and 410)

[new_logs.zip](https://github.com/boundlessgeo/qgis-geoserver-plugin/files/1109199/new_logs.zip)

**Comment by luipir** [comment]
AuthCatalogXMLCacheTime error was due the lack of default initialization

**Comment by luipir** [comment]
btw this does not explain errors like: 
'NoneType' object has no attribute <....>
I just verified that this kind of errors is not present (or less frequent) in case of restarting qgis after loaded plugins or in general, before to start the test:

sono other notes:
This error (NoneType) is not present testing on Linux or OSX (python 2.7.12) but only present in Windows (python 2.7.5)
