### ISSUE TITLE
Implement drag&drop from Layers panel to add layers to Workspace

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geoserver-plugin#9]
Add layers to geoserver via drag&drop is implemented when source is the browser panel, but not implemented if source is a layer visible in Layer panel (QgsLegendInterface - QgsLayerTreeView)

the behaviour would be similar to that applied when layer is dragged from Browser

**Comment by alexbruy** [comment]
Pull request #26 submitted
