### ISSUE TITLE
Plugin is not able to get server information

### ISSUE THREAD

**Issue by SrNetoChan** [boundlessgeo/qgis-geoserver-plugin#92]
The plugin is not able to get and display information from the server. Even if you hit restart.

![image](https://user-images.githubusercontent.com/3607161/45294017-d6e12f00-b4f1-11e8-9bb2-1affea3acd1c.png)

Tested against geoserver 2.12.5

**Comment by volaya** [comment]
Is this with plain geoserver, or BS server?

**Comment by SrNetoChan** [comment]
this is plain geoserver 2.12.5

**Comment by SrNetoChan** [comment]
Because of our talk, I opened a ticket on gsconfig:

https://github.com/boundlessgeo/gsconfig/issues/191
