### ISSUE TITLE
Label distance in QGIS does not look the same as in openlayers

### ISSUE THREAD

**Issue by SrNetoChan** [boundlessgeo/qgis-geoserver-plugin#93]
Opening the Manhattan (NY) points of interest layer (which is provided with Geoserver) on QGIS 3, the labels don't seem to be at the same distance as seen on OpenLayers.

QGIS:

![image](https://user-images.githubusercontent.com/3607161/45310710-f80c4480-b51e-11e8-97cf-3348b754b759.png)

Geoserver on Openlayers:

![image](https://user-images.githubusercontent.com/3607161/45311487-2559f200-b521-11e8-9bae-bdf1312c261f.png)

QGIS settings:

![image](https://user-images.githubusercontent.com/3607161/45310799-30138780-b51f-11e8-8ed0-e99b01db9a98.png)

Geoserver Style:

![image](https://user-images.githubusercontent.com/3607161/45311185-4837d680-b520-11e8-9c16-ceb1ee7416ca.png)

Seems that the issue as something to do with the units. QGIS uses millimeters. From QGIS 3 on, it's possible to use pixels as well, so maybe it's easy to fix.

**Comment by volaya** [comment]
Now units are automatically set to pixels for all layers added from GS to the project

Should be fixed

**Comment by SrNetoChan** [comment]
Fixed
